version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  fastify:
    image: fastify
    container_name: fastify
    hostname: fastify
    build:
      context: ./fastify
      dockerfile: Containerfile
    volumes:
      - ./fastify/src/:/opt/fastify/src
    depends_on:
      - mongo
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017
      FASTIFY_COOCKIE_SECRET: 3ec31422be4af342cf79e3170d7db3aec59f977211a1d2b7a94233ac25ea1b21
      FASTIFY_JWT_SECRET: 11efedb0c7ef5ac7a5f35b1a215a6a14307db52a7b97ea3b43e72a6fe53b593a

  react:
    image: react
    container_name: react
    hostname: react
    build:
      context: ./react
      dockerfile: Containerfile
    volumes:
      - ./react/src/:/opt/react/src
    depends_on:
      - fastify
    restart: always
    environment:
      VITE_API_URL: "http://localhost:3000"

  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    build:
      context: ./nginx
      dockerfile: Containerfile
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 80:80
      # - 443:443
    restart: always
    depends_on:
      - fastify
      - react
